# Generated by Django 5.0.2 on 2024-03-02 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_alter_inventorymaster_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaster',
            name='category_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 19, 56, 37, 162271), null=True),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 19, 56, 37, 163270), null=True),
        ),
    ]
