# Generated by Django 5.0.2 on 2024-03-02 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0005_alter_inventorymaster_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 19, 57, 2, 835652), null=True),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 19, 57, 2, 836652), null=True),
        ),
    ]
