# Generated by Django 5.0.2 on 2024-03-02 14:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0007_alter_inventorymaster_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymaster',
            name='category_name',
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='fk_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website_app.categorymaster'),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 20, 4, 16, 660189), null=True),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 20, 4, 16, 660189), null=True),
        ),
    ]
