# Generated by Django 5.0.2 on 2024-03-02 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0010_alter_inventorymaster_created_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmaster',
            old_name='customer_addr',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='salesmaster',
            old_name='customer_email',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='salesmaster',
            old_name='customer_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='salesmaster',
            old_name='customer_phone',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='salesmaster',
            old_name='discount',
            new_name='fax_no',
        ),
        migrations.RenameField(
            model_name='salesmaster',
            old_name='total_amt',
            new_name='mobile_no',
        ),
        migrations.AddField(
            model_name='salesmaster',
            name='phone_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salesmaster',
            name='postal_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salesmaster',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 21, 52, 11, 285546), null=True),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 21, 52, 11, 285546), null=True),
        ),
    ]
