# Generated by Django 5.0.2 on 2024-03-02 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0012_countrymaster_alter_inventorymaster_created_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statemaster',
            old_name='country_id',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 22, 9, 13, 385539), null=True),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 22, 9, 13, 385539), null=True),
        ),
    ]
