# Generated by Django 5.0.2 on 2024-03-02 17:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0014_alter_inventorymaster_created_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 22, 55, 49, 910000), null=True),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website_app.citymaster'),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website_app.countrymaster'),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 22, 55, 49, 925627), null=True),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='fk_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website_app.inventorymaster'),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website_app.statemaster'),
        ),
    ]
