# Generated by Django 5.0.2 on 2024-03-02 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0015_alter_inventorymaster_created_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmaster',
            old_name='city',
            new_name='cities',
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 22, 57, 56, 51084), null=True),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 22, 57, 56, 51084), null=True),
        ),
    ]
