# Generated by Django 5.0.2 on 2024-03-03 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0016_rename_city_salesmaster_cities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('purchased_dt', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('mail', models.CharField(blank=True, max_length=200, null=True)),
                ('other_link', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 10, 49, 47, 185582), null=True),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 10, 49, 47, 185582), null=True),
        ),
    ]
