# Generated by Django 5.0.2 on 2024-04-10 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0022_admin_alter_inventorymaster_created_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesproducts',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 10, 23, 54, 52, 134906), null=True),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 10, 23, 54, 52, 132906), null=True),
        ),
        migrations.AlterField(
            model_name='purchasedmaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 10, 23, 54, 52, 132906), null=True),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 10, 23, 54, 52, 133905), null=True),
        ),
    ]
